[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=1
lib_deps =
  https://github.com/Seeed-Projects/Seeed_GxEPD2.git
  https://github.com/olikraus/U8g2_for_Adafruit_GFX.git
  bblanchon/StreamUtils @ ^1.9.0
