[env:seeed_xiao_esp32s3]
platform = espressif32 @ 7.1.3
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=1
lib_deps =
  https://github.com/Seeed-Projects/Seeed_GxEPD2.git#1100ea37c16b910fd79152f4250c13d802b9c20b
  https://github.com/olikraus/U8g2_for_Adafruit_GFX.git#82d2b3eea866e7d40266672b41e5c8306ee97403
  adafruit/Adafruit GFX Library @ 1.12.6
  adafruit/Adafruit BusIO @ 1.17.4
